resources:

- name: source-code
  type: git
  check_every: 5s
  source:
    uri: https://github.com/altfatterz/s1p-2018-contract-testing.git
    branch: master

- name: pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{USERNAME}}
    password: {{PASSWORD}}
    organization: {{ORG}}
    space: {{SPACE}}
    skip_cert_check: false

jobs:

- name: build-person-service
  plan:
  - get: source-code
    trigger: true
  - task: package
    file: source-code/ci/tasks/package-person.yml

- name: deploy-person-service
  plan:
  - put: pws
    params:
      manifest: source-code/person-service/manifest.yml
      current_app_name: {{PERSON-SERVICE-APP-NAME}}

- name: build-myaccount-client
  plan:
  - get: source-code
    passed:
    - build-person-service
    trigger: true
  - task: package
    file: source-code/ci/tasks/package-myaccount.yml

- name: deploy-myaccount-client
  plan:
  - put: pws
    params:
      manifest: source-code/myaccount-client/manifest.yml
      current_app_name: {{MYACCOUNT-CLIENT-APP-NAME}}
      environment_variables:
        personservice: https://{{PERSON-SERVICE-APP-NAME}}.cfapps.io
